### PR TITLE
ci: disable strict status checks

### PR DESCRIPTION
**Pull request by mattdibi**

### CODE REVIEW

**Comment by netomi** [comment]
I created a template function to avoid duplicating the same settings again and again. Also if a setting is equal to the default, you can just omit it.

btw. there is a playground available at https://eclipse-kura.github.io/.eclipsefdn/playground/ where you can play around with jsonnet and experiment with it easily.

**Comment by mattdibi** [comment]
> I created a template function to avoid duplicating the same settings again and again. Also if a setting is equal to the default, you can just omit it.
> 
> btw. there is a playground available at https://eclipse-kura.github.io/.eclipsefdn/playground/ where you can play around with jsonnet and experiment with it easily.

Thanks for chiming in again. I was looking at the playground and just about started climbing the learning curve for Otterdog/Jsonnet. I didn't know Jsonnet was capable of this. I appreciate the pointers.

One question: we currently have one issue with the branch protection rules. In the past our Project Lead @MMaiero, had the permissions to force a PR merge without waiting/satisfying the required status checks. This was used when we were in a hurry and needed to change stuff that don't require checks (i.e. Release Notes, README changes etc...). What's the best way to achieve this? Can @MMaiero be set as "Admin" so that we can leverage the `is_admin_enforced:false` option?

**Comment by netomi** [comment]
so, if there are required status checks, you cant pass by them in branch protection rules. Various project have these requirements, but there is a workaround.

Use rulesets instead, that are basically the same as branch protection rules, but offer more options and have bypass rules that are also working with status checks, see for example for the zenoh project:

https://github.com/eclipse-zenoh/.eclipsefdn/blob/main/otterdog/eclipse-zenoh.jsonnet#L3

there everybody with write permissions can bypass, you should probably limit that to a project lead in your case then, there is the team https://github.com/orgs/eclipse-kura/teams/iot-kura-project-leads

**Comment by netomi** [comment]
actually another option that might be acceptable is to enable auto_merge for the repo. This means that the PR will be automatically merged once all required status checks have passed. So if you have some checks that take a while but the PR is small and changes e.g. the README as you say, you can review and then click the auto merge button in the PR.

You dont have to wait for all status checks to complete, the merging will happen automatically.

**Review by MMaiero — APPROVED** [review]

**Pull request merged**
